name: add_to_gallery_example
description: Demonstrates how to use the add_to_gallery plugin
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  image_picker: ^0.7.5+4
  path_provider: ^2.0.2
  http: ^0.13.3
  path: ^1.8.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  add_to_gallery:
    path: ../

flutter:
  uses-material-design: true

  assets:
   - assets/local-image-1.jpg
   - assets/local-image-2.jpg
