name: save_to_gallery
description: Saves images and videos from network or temporary file to external storage. Both images and videos will be visible in Android Gallery and iOS Photos.
version: 0.1.0
homepage: https://github.com/flowmobile/save_to_gallery

environment:
  sdk: '>=2.12.0 <3.0.0'

module:
 androidX: true

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  http: ^0.13.1
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: flowmobile.save_to_gallery
        pluginClass: SaveToGalleryPlugin
      ios:
        pluginClass: SaveToGalleryPlugin


